### ISSUE TITLE
constraint specification results in an error when hyphen is involved

### ISSUE THREAD

**Issue by Takeshi-1970** [sassoftware/sasoptpy#5] opened 2020-04-07 05:01 UTC
One can add constraints using model.add_constraints such as :

model.add_constraints((x[i] <= 5*value[i] for i in XS  ))

into a model.  However, if value of XS  includes '-' (hyphen) , it causes an  error 
and converted OPTMODEL does not execute.  Is there any way to workaround,
other than removing hyphen ?

Here is a simple code to test.

import pandas as pd
import saspy
s = saspy.SASsession(cfgname='winlocal')

import sasoptpy as so 
model = so.Model(name="Test Model", session=s)

x_data = pd.DataFrame([
    ['x-1',2],
    ['x-2',3],
    ['x-3',4]
],columns=['time','value']).set_index(['time'])

XS=x_data.index.tolist()
value=x_data['value']

x=model.add_variables(XS, vartype=so.CONT,  lb=0, name='x')
model.add_constraints((x[i] <= 5*value[i] for i in XS  ))

Total = so.quick_sum ( value[i]*x[i] for i in XS  )
model.set_objective(Total, sense=so.MAX, name='TotalValue')
status=model.solve()
status

**Comment by sertalpbilal** [comment] 2020-04-07 05:41
This is a restriction from PROC OPTMODEL, as you mentioned. Hyphens in the names are not supported, so it will cause an error. Replacing hyphens is the only option.

``` python
x_data = pd.DataFrame([
['x-1',2],
['x-2',3],
['x-3',4]
],columns=['time','value'])
x_data['time_str'] = x_data['time'].str.replace('-', '')

x_data = x_data.set_index(['time_str'])
```

**Comment by Takeshi-1970** [comment] 2020-04-07 05:50
Even if hyphen is used on OPTMODEL procedure, the following code would work.

proc optmodel;
var x {{'x-1','x-2','x-3'}} >= 0;
num upper{{'x-1','x-2','x-3'}}=[10 15 20];

con c010 { s in {'x-1','x-2','x-3'}} : x[s] <= upper[s];
max TotalValue = 2 * x['x-1'] + 3 * x['x-2'] + 4 * x['x-3']; 
solve;
print _var_.name _var_.lb _var_.ub _var_ _var_.rc;
print _con_.name _con_.body _con_.dual;
quit;

Did I overlook something ?

**Comment by Kimiko2019** [comment] 2020-04-07 05:53
Since sasoptpy is nice to use for the optimization problems, we are now expanding areas to use. In this process we need to accept product code which has “-” in the string. 

I think OPTMODEL(SAS/OR) has a different rule from sasoptpy.

<<OPTMODEL(SAS/OR)>>

When we have a constraint like

con Capacity {s in SITES}:  sum {c in CUSTOMERS} y_arc[s,c]*customer_demand[c] <= site_capacity[s];

It makes the constraint name like;

Constraint Capacity['site-01']: 0.3519911181*y_arc['site-01','cust-01'] + 1.8215406741*        
y_arc['site-01','cust-02'] + 7.0679658312*y_arc['site-01','cust-03'] + 3.905491379*            
y_arc['site-01','cust-04'] + 6.8837843541*y_arc['site-01','cust-05'] + 1.5399381106*           
y_arc['site-01','cust-06'] + 5.6588416526*y_arc['site-01','cust-07'] + 4.1762284628*           
y_arc['site-01','cust-08'] + 1.8362310677*y_arc['site-01','cust-09'] <= 2689.9487258           

<< sasoptpy >>

When we have a constraint like

model.add_constraints((
        (so.quick_sum(y_arc[s,c]*customer_demand[c] for c in CUSTOMERS) <= site_capacity[s]) 
        for s in SITES),name='Capacity')

Then it returns like;

con Capacity_site-01 : 0.3519911181 * y_arc['site-01', 'cust-01'] + 1.8215406741 * y_arc['site-01', 'cust-02'] + 7.0679658312 * y_arc['site-01', 'cust-03'] + 3.905491379 * y_arc['site-01', 'cust-04'] + 6.8837843541 * y_arc['site-01', 'cust-05'] + 1.5399381106 * y_arc['site-01', 'cust-06'] + 5.6588416526 * y_arc['site-01', 'cust-07'] + 4.1762284628 * y_arc['site-01', 'cust-08'] + 1.8362310677 * y_arc['site-01', 'cust-09'] <= 2689.9487258;

Can’t we expect same naming rule for both?

**Comment by sertalpbilal** [comment] 2020-04-07 06:01
> Even if hyphen is used on OPTMODEL procedure, the following code would work.
> 
> proc optmodel;
> var x {{'x-1','x-2','x-3'}} >= 0;
> num upper{{'x-1','x-2','x-3'}}=[10 15 20];
> 
> con c010 { s in {'x-1','x-2','x-3'}} : x[s] <= upper[s];
> max TotalValue = 2 * x['x-1'] + 3 * x['x-2'] + 4 * x['x-3'];
> solve;
> print _var_.name _var_.lb _var_.ub _var_ _var_.rc;
> print _con_.name _con_.body _con_.dual;
> quit;
> 
> Did I overlook something ?

You are right, I just noticed and was testing why it is not working. What message do you get when you submit the code?

**Comment by Kimiko2019** [comment] 2020-04-07 06:05
I put log, but it does not have any extra message. 

NOTE: Converting model Test_Model to OPTMODEL.
NOTE: Submitting OPTMODEL codes to SAS server.
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
               ______   _
               525      22
                        76
               ______   _
               525      22
                        76
               ______   _
               525      22
                        76
NOTE: Problem generation will use 4 threads.
NOTE: Previous errors might cause the problem to be resolved incorrectly.
NOTE: The problem has 3 variables (0 free, 0 fixed).
NOTE: The problem has 0 linear constraints (0 LE, 0 EQ, 0 GE, 0 range).
NOTE: The problem has 0 nonlinear constraints (0 LE, 0 EQ, 0 GE, 0 range).
NOTE: The OPTMODEL presolver is disabled for linear problems.
NOTE: The problem is a pure network instance. The ALGORITHM=NETWORK option is recommended for solving problems with this structure.
NOTE: The LP presolver value AUTOMATIC is applied.
NOTE: The LP presolver time is 0.00 seconds.
NOTE: The LP presolver found this problem to be unbounded.
NOTE: Unbounded.
NOTE: The data set WORK.PROB_SUMMARY has 14 observations and 3 variables.
NOTE: The data set WORK.SOL_SUMMARY has 8 observations and 3 variables.
NOTE: The data set WORK.PRIMAL_OUT has 3 observations and 6 variables.
NOTE: The data set WORK.DUAL_OUT has 0 observations and 4 variables.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE OPTMODEL used (Total process time):
      real time           0.12 seconds
      cpu time            0.10 seconds

**Comment by Takeshi-1970** [comment] 2020-04-07 06:12
I had a little more information on error part.

NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
               _______   _
               525       22
                         76
              INTER, SYMDIFF, TO, UNION, ^, ^=, ||, ~=.  
               _______   _
               525       22
                         76
              INTER, SYMDIFF, TO, UNION, ^, ^=, ||, ~=.  
               _______   _
               525       22
                         76
              INTER, SYMDIFF, TO, UNION, ^, ^=, ||, ~=.  
NOTE: Problem generation will use 4 threads.

**Comment by sertalpbilal** [comment] 2020-04-07 06:15
Ok, here is the problem:
When generating constraint names, index keys are getting appended to constraint name. If you run
``` python
print(model.to_optmodel())
```
you will see
```
con con_1_x-1 : x['x-1'] <= 10;
con con_1_x-2 : x['x-2'] <= 15;
con con_1_x-3 : x['x-3'] <= 20;
```
which is invalid for PROC OPTMODEL.

One way to fix it for now is to use a wrapper for the XS index, just like this:
``` python
model.add_constraints((x[XS[i]] <= 5*value[XS[i]] for i in range(len(XS)) ))
```

This should fix the problem.
```
con con_1_0 : x['x-1'] <= 10;
con con_1_1 : x['x-2'] <= 15;
con con_1_2 : x['x-3'] <= 20;
```

I am adding this example to my unit test for the v1.0.0 release, which will be released soon.

**Comment by sertalpbilal** [comment] 2020-04-07 06:23
By the way, if you would like to try the pre-release (1.0.0-alpha.2) install it via pip:
``` bash
pip3 install sasoptpy==1.0.0a2
```
and run the same example, by adding a name to the constraint:
``` python
model = so.Model(name="Test Model", session=s)

x_data = pd.DataFrame([
['x-1',2],
['x-2',3],
['x-3',4]
],columns=['time','value']).set_index(['time'])

XS=x_data.index.tolist()
value=x_data['value']

x=model.add_variables(XS, vartype=so.CONT, lb=0, name='x')
model.add_constraints((x[i] <= 5*value[i] for i in XS ), name='c')

Total = so.quick_sum ( value[i]*x[i] for i in XS )
model.set_objective(Total, sense=so.MAX, name='TotalValue')
status=model.solve()
status
```
This will give you the following OPTMODEL code:
``` sas
>>> print(model.to_optmodel())
proc optmodel;
   var x {{'x-1','x-2','x-3'}} >= 0;
   con c_x_1 : x['x-1'] <= 10;
   con c_x_2 : x['x-2'] <= 15;
   con c_x_3 : x['x-3'] <= 20;
   max TotalValue = 2 * (x['x-1']) + 3 * (x['x-2']) + 4 * (x['x-3']);
   solve;
quit;
```

**Comment by Kimiko2019** [comment] 2020-04-07 06:28
You mean you solve the “-“ only?
Honestly, we also have the length problem when I put some loop like;

model.add_constraints((y[a,t,r] == 0 for a in ACTIVITIES for t in OUTTIMEBUCKETS  for r in RESOURCES), name="c010")

This brings the more than 32 character length of constraint name. Then those constraints are considered same constraint, then it make the result wrong.

**Comment by sertalpbilal** [comment] 2020-04-07 06:38
Kimiko, if you want you can send me the full problem, I was replying the original question. I am aware of the 32 character length limit, we have a package option for replacing them at runtime in the new release.
`replace_long_names` is the function: https://github.com/sassoftware/sasoptpy/blob/762b2888bd5f238443c0768ec2db1fe44d94404d/sasoptpy/interface/util.py#L29
This is how you call the option `limit_names`:

https://github.com/sassoftware/sasoptpy/blob/762b2888bd5f238443c0768ec2db1fe44d94404d/tests/interface/test_sas_interface.py#L76

**Comment by Kimiko2019** [comment] 2020-04-07 07:03
Thank you for your links. I will read them.  And I put the converted code which "our way of rapper"  for the above small example. I am doing the same thing for the original code. 

I will check your link and I will decide whether your pre-release version.

#!/usr/bin/env python
# coding: utf-8

import pandas as pd
x_data = pd.DataFrame([
    ['x-1',2],
    ['x-2',3],
    ['x-3',4]
],columns=['time','value']).set_index(['time'])

x_data.reset_index()
tmp_df=x_data.reset_index().reset_index()
tmp_df['index']=tmp_df['index'].astype('str')
tmp_df['ID']=tmp_df['index'].str.rjust(8, "a")
tmp_df=tmp_df.drop("index", axis=1)

tmp1_df=pd.DataFrame(tmp_df).set_index("ID")
ID2name=tmp1_df["time"]

import saspy
s = saspy.SASsession(cfgname='winlocal')
import sasoptpy as so  
model = so.Model(name="Test Model", session=s)

XS=tmp1_df.index.tolist()
value=tmp1_df['value']
x=model.add_variables(XS, vartype=so.CONT,  lb=0, name='x')
model.add_constraints((x[i] <= 5*value[i] for i in XS  ),name='c010')
Total = so.quick_sum ( value[i]*x[i] for i in XS  )
model.set_objective(Total, sense=so.MAX, name='TotalValue')

status=model.solve()
status

for i in XS:
    print (ID2name[i], x[i].get_value())

**Comment by sertalpbilal** [comment] 2020-04-07 13:19
Looks like it generates a valid OPTMODEL code with the wrapper. I am closing the issue but feel free to reopen if you have a follow-up.

**Closed by sertalpbilal** 2020-04-07 13:19 UTC
